version: '2'

volumes:
  # for persistence between restarts
  postgres_data: {}

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports: #make db accessible locally
      - "127.0.0.1:5432:5432"
    env_file: env

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db